### ISSUE TITLE
Include libgda

### ISSUE THREAD

**Issue by bilelmoussaoui** [elementary/flatpak-platform#20]
As most of the Vala apps uses it for sqlite/whatever database stuff, and it's pretty complex to properly build. Maybe it's worth having it on the elementary platform by default?

**Comment by danrabbit** [comment]
Here's what Music currently has for GDA:

```
  - name: gda
    config-opts:
      - '--with-java=no'
      - '--with-jni=no'
      - '--with-oracle=no'
      - '--with-help=no'
      - '--with-ui=no'
      - '--disable-tools'
      - '--enable-vala'
    sources:
      - type: archive
        url: https://download.gnome.org/sources/libgda/5.2/libgda-5.2.9.tar.xz
        sha256: 59caed8ca72b1ac6437c9844f0677f8a296d52cfd1c0049116026abfb1d87d9b
    modules:
      - name: intltool
        cleanup:
          - '*'
        sources:
          - type: archive
            url: https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
            md5: 12e517cac2b57a0121cda351570f1e63
```
