### ISSUE TITLE
Include LibCanberra

### ISSUE THREAD

**Issue by danrabbit** [elementary/flatpak-platform#21]
It seems Camera and Screenshot use this. I wonder if it's worth including?

```
  - name: canberra
    config-opts:
      - '--enable-gstreamer'
      - '--enable-pulse'
      - '--disable-oss'
      - '--disable-static'
      - '--with-builtin=dso'
    sources:
      - type: git
        url: http://git.0pointer.net/clone/libcanberra.git
        disable-shallow-clone: true
```
